package br.com.pegasus.api.restful.repository.embeddable;
/**
 * ----
 * Shared Models Library
 * Definições reutilizáveis para múltiplas APIs
 * The version of the OpenAPI document: 1.0.0
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * ----
 */

// IMPORT - FIXED

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder(toBuilder = true)
@AllArgsConstructor
@RequiredArgsConstructor
@EqualsAndHashCode
@Embeddable
public final class ResistanceEntity {

    @Column(name = "PHYSICAL_RESISTENCE")
    private int physical;

    @Column(name = "MAGIC_RESISTENCE")
    private int magic;

}
