openapi: 3.0.0

info:
  version: 1.0.0
  title: Registro de Personagens
  description: >
    API REST para cadastro, consulta, atualização 
    e exclusão de dados de Personagem.
  termsOfService: https://swagger.io/terms/
  contact:
    email: cadastro@minhaliga.com.br
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: Saiba mais sobre MINHA LIGA em
  url: https://www.minhaliga.com.br


servers:
  - url: http://localhost:8080/minhaliga/v1
    description: Servidor local - versão v1.

tags:
  - name: personagens
    description: Gerenciamento de personagens.

paths:
  '/':
    get:
      tags: [ personagens ]
      operationId: personagensGetPage
      summary: Pagina de personagems
      description: Retorna a pagina da lista de personagens cadastrado.
      parameters:
        - $ref: '#/components/parameters/page-query'
        - $ref: '#/components/parameters/size-query'
      responses:
        "200":
          $ref: '#/components/responses/get-page-response'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    post:
      tags: [ personagens ]
      operationId: personagensCreate
      summary: Cria um novo personagem
      description: Cria um novo personagem.
      requestBody:
        $ref: '#/components/requestBodies/create-request'
      responses:
        "201":
          $ref: '#/components/responses/create-response'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

  '/{id}':
    parameters:
      - $ref: '#/components/parameters/id-path'

    get:
      tags: [ personagens ]
      operationId: personagensGet
      summary: Obtem um personahem pelo id
      description: Consulta detalhes de um personagem existente pelo id.
      responses:
        "200":
          $ref: '#/components/responses/get-response'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    put:
      tags: [ personagens ]
      operationId: personagensUpdate
      summary: Atualiza personagem
      description: Atualiza os dados de um personagem.
      requestBody:
        $ref: '#/components/requestBodies/update-request'
      responses:
        "200":
          $ref: '#/components/responses/update-response'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    delete:
      tags: [ personagens ]
      operationId: loginDelete
      summary: Delete login
      description: Remove permanentemente o login informado.
      responses:
        "200":
          $ref: '#/components/responses/delete-response'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

components:

  parameters: # [Estruturas de query, path, header e cookie]
    id-path:
      description: Id do personagem.
      required: true
      in: path
      name: id
      schema:
        $ref: '#/components/schemas/id-field'

    page-query:
      description: Índice da página (0-based)
      required: false
      in: query
      name: page
      schema:
        $ref: '#/components/schemas/page-field'

    size-query:
      description: Tamanho da página
      required: false
      in: query
      name: size
      schema:
        $ref: '#/components/schemas/size-field'

  requestBodies: # [Estruturas de requisições]

    create-request:
      description: Requisição de criação.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemCreateBodyRequestType'

    update-request:
      description: request de atualização.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemUpdateBodyRequestType'

  responses: # [Estruturas de respostas de uma requisições]

    # [RESPONSE.SUCCESS]
    get-page-response:
      description: Retorna a pagina solicitada.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemPageResponseType'

    get-response:
      description: Retorna o elemento solicitao.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemGetResponseType'

    create-response:
      description: Retorna o elemento criado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemCreateBodyResponseType'

    update-response:
      description: Retorna o elemento atualizado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemUpdateBodyResponseType'

    delete-response:
      description: Retorna o elemento deletado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemDeleteBodyResponseType'

    # [RESPONSE.FAIL]
    bad-request-response:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemExceptionResponseType'

    not-found-response:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemExceptionResponseType'

    conflict-response:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemExceptionResponseType'

    internal-server-error-response:
      description: Erro interno no servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PersonagemExceptionResponseType'


  schemas: # Modelos de dados :: field, type, body, request e response

    # [FIELD]
    size-field:
      type: integer
      minimum: 0
      default: 0
    id-field:
      type: integer
      minimum: 1
      default: 20

    page-field:
      type: integer
      minimum: 0
      default: 0

    nome-field:
      type: string
      description: Nome do personagem.
      minLength: 5
      maxLength: 150
      example: Personagem

    list-string-field:
      type: array
      items:
        type: string

    # [Type]
    DanoType:
      type: object
      description: ''
      properties:
        fisico:
          type: integer
        magico:
          type: integer

    ResistenciaType:
      type: object
      description: ''
      properties:
        fisico:
          type: integer
        magico:
          type: integer

    AtributosType:
      type: object
      description: ''
      properties:
        vida:
          type: integer
        dano:
          $ref: '#/components/schemas/DanoType'
        resistencia:
          $ref: '#/components/schemas/ResistenciaType'
        habilidadeList:
          $ref: '#/components/schemas/list-string-field'

    PersonagemType:
      type: object
      properties:
        personagemId:
          $ref: '#/components/schemas/id-field'
        racaId:
          $ref: '#/components/schemas/id-field'
        classeId:
          $ref: '#/components/schemas/id-field'
        nome:
          $ref: '#/components/schemas/nome-field'
        atributos:
          $ref: '#/components/schemas/AtributosType'

    UpdatePersonagemType:
      type: object
      properties:
        racaId:
          $ref: '#/components/schemas/id-field'
        classeId:
          $ref: '#/components/schemas/id-field'
        nome:
          $ref: '#/components/schemas/nome-field'

    CreatePersonagemType:
      type: object
      properties:
        nome:
          $ref: '#/components/schemas/nome-field'
        classe:
          type: integer
        raca:
          type: integer

    # [REQUEST.BODY]
    PersonagemCreateBodyRequestType:
      type: object
      properties:
        create:
          $ref: '#/components/schemas/CreatePersonagemType'

    PersonagemUpdateBodyRequestType:
      type: object
      properties:
        racaId:
          $ref: '#/components/schemas/id-field'
        classeId:
          $ref: '#/components/schemas/id-field'
        nome:
          $ref: '#/components/schemas/nome-field'

    # [RESPONSE.BODY]
    PersonagemDeleteBodyResponseType:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusResponseType'

    PersonagemUpdateBodyResponseType:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusResponseType'

    PersonagemCreateBodyResponseType:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusResponseType'
        data:
          $ref: '#/components/schemas/PersonagemType'

    PersonagemGetResponseType:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusResponseType'
        data:
          $ref: '#/components/schemas/PersonagemType'

    PersonagemPageResponseType:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusResponseType'
        pagination:
          $ref: '#/components/schemas/paginationType'
        data:
          type: array
          items:
            $ref: '#/components/schemas/PersonagemType'

    PersonagemExceptionResponseType:
      type: object
      description: Modelo padrão para erros
      properties:
        status:
          $ref: '#/components/schemas/StatusResponseType'
        details:
          type: array
          items:
            type: string
          description: Detalhes do erro ocorrido.
          example: ["Mensagem de erro1"]

    # [TYPE]
    StatusResponseType:
      type: object
      description: Wrapper genérico para respostas com status
      properties:
        code:
          $ref: '#/components/schemas/StatusEnum'
        message:
          $ref: '#/components/schemas/MessageEnum'

    paginationType:
      type: object
      description: Modelo padrão para erros
      properties:
        quantity:
          type: integer
          description: Total de itens da lista.
          example: 123
        currentPage:
          type: integer
          description: Página atual (0-based).
          example: 0
        itemsPerPage:
          type: integer
          description: Itens por página.
          example: 20
        totalPages:
          type: integer
          description: Total de páginas disponíveis.
          example: 7
        hasNextPage:
          type: boolean
          description: Se existe próxima página.
          example: true

    # [ENUM]
    StatusEnum:
      type: integer
      description: Código do erro
      enum:
        - 200
        - 400
        - 404
        - 409
        - 500
      x-enum-varnames:
        - OK
        - BAD_REQUEST
        - NOT_FOUND
        - CONFLICT
        - INTERNAL_SERVER_ERROR
      example: 200

    MessageEnum:
      type: string
      description: Código do erro
      enum:
        - "SUCCESS"
        - "CREATED"
        - "Bad request"
        - "Not found"
        - "Conflict"
        - "Internal server error"
      x-enum-varnames:
        - OK
        - CREATE
        - BAD_REQUEST
        - NOT_FOUND
        - CONFLICT
        - INTERNAL_SERVER_ERROR
      example: SUCCESS





####
####
####
####
####