openapi: 3.0.0

info:
  version: 1.0.0
  title: Registro de Personagens
  description: >
    API REST para cadastro, consulta, atualização 
    e exclusão de dados de Character.
  termsOfService: https://swagger.io/terms/
  contact:
    email: cadastro@minhaliga.com.br
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: Saiba mais sobre MINHA LIGA em
  url: https://www.minhaliga.com.br

servers:
  - url: http://localhost:8080/minhaliga/v1
    description: Servidor local - versão v1.

tags:
  - name: characters
    description: Gerenciamento de personagens.

paths:
  '/':
    get:
      tags: [ characters ]
      operationId: characterGetPage
      summary: Pagina de personagems
      description: Retorna a pagina da lista de personagens cadastrado.
      parameters:
        - $ref: '#/components/parameters/page-query'
        - $ref: '#/components/parameters/size-query'
      responses:
        "200":
          description: Retorna a pagina solicitada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterPageResponseType'
        "400":
          $ref: '#/components/responses/page-bad-request-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    post:
      tags: [ characters ]
      operationId: characterCreate
      summary: Cria um novo personagem
      description: Cria um novo personagem.
      requestBody:
        description: Requisição de criação.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacterCreateBodyType'
      responses:
        "201":
          description: Retorna o elemento criado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterCreateResponseType'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

  '/{id}':
    parameters:
      - $ref: '#/components/parameters/id-path'

    get:
      tags: [ characters ]
      operationId: characterGet
      summary: Obtem um personahem pelo id
      description: Consulta detalhes de um personagem existente pelo id.
      responses:
        "200":
          description: Retorna o elemento solicitao.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterGetResponseType'
        "400":
          $ref: '#/components/responses/get-delete-bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    put:
      tags: [ characters ]
      operationId: characterUpdate
      summary: Atualiza personagem
      description: Atualiza os dados de um personagem.
      requestBody:
        description: request de atualização.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CharacterUpdateBodyType'
      responses:
        "200":
          description: Retorna o elemento atualizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterUpdateResponseType'
        "400":
          $ref: '#/components/responses/bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

    delete:
      tags: [ characters ]
      operationId: characterDelete
      summary: Delete login
      description: Remove permanentemente o login informado.
      responses:
        "200":
          description: Retorna o elemento deletado.
        "400":
          $ref: '#/components/responses/get-delete-bad-request-response'
        "404":
          $ref: '#/components/responses/not-found-response'
        "500":
          $ref: '#/components/responses/internal-server-error-response'

components:

  # [ESTRUTURAS :: QUERY, PATH, HEADER E COOKIE]
  parameters:
    id-path:
      description: Id do personagem.
      required: true
      in: path
      name: id
      schema:
        $ref: '#/components/schemas/id-field'

    page-query:
      description: Índice da página (0-based)
      required: false
      in: query
      name: page
      schema:
        $ref: '#/components/schemas/page-field'

    size-query:
      description: Tamanho da página
      required: false
      in: query
      name: size
      schema:
        $ref: '#/components/schemas/size-field'

  # [ESTRUTURAS DE REQUISIÇÕES]
  # requestBodies:

  # [ESTRUTURAS DE RESPOSTAS DE UMA REQUISIÇÕES]
  responses:
    bad-request-response:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestType'

    page-bad-request-response:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PageBadRequestType'

    get-delete-bad-request-response:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DeleteBadRequestType'

    not-found-response:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFoundType'

    conflict-response:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConflictType'

    internal-server-error-response:
      description: Erro interno no servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternalServerEerrorType'

  schemas: # Modelos de dados :: field, type, body, request e response

    # [FIELD]
    size-field:
      type: integer
      minimum: 0
      default: 0

    id-field:
      type: integer

    page-field:
      type: integer
      minimum: 0
      default: 0

    char-name-field:
      type: string
      description: Nome do personagem.
      minLength: 5
      maxLength: 150
      example: Character

    skils-field:
      type: array
      items:
        type: string

    # [TYPE :: REQUEST]
    paginationType:
      type: object
      description: 'Modelo padrão para erros.'
      properties:
        page:
          type: integer
          description: 'Página atual (0-based).'
          example: 10
        size:
          type: integer
          description: 'Tamanho da página.'
          example: 30
        totalElements:
          type: integer
          format: int64
          description: 'Total de registros.'
          example: 300
        totalPages:
          type: integer
          description: 'Total de páginas (com bare no size).'
          example: 10
        hasPrevious:
          type: boolean
          description: 'Se há página anterior.'
          example: true
        hasNext:
          type: boolean
          description: 'Se há página posterior.'
          example: false

    # [TYPE :: REQUEST :: BODY]
    CharacterCreateBodyType:
      type: object
      properties:
        charName:
          $ref: '#/components/schemas/char-name-field'
        charClassId:
          $ref: '#/components/schemas/id-field'
        charRaceId:
          $ref: '#/components/schemas/id-field'

    CharacterUpdateBodyType:
      type: object
      properties:
        charName:
          $ref: '#/components/schemas/char-name-field'
        charRaceId:
          $ref: '#/components/schemas/id-field'
        charClassId:
          $ref: '#/components/schemas/id-field'

    # [TYPE :: RESPONSE :: GERAL]
    ExceptionResponseType:
      type: object
      description: Modelo padrão para erros
      properties:
        details:
          type: array
          items:
            type: string
          description: Detalhes do erro ocorrido.
          example: ["Mensagem de erro 1"]

    BadRequestType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "O campo Name é obrigatório"
              - "O campo CharClassId é obrigatório"
              - "O campo CharRaceId é obrigatório"

    PageBadRequestType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "O campo Page é obrigatório"
              - "O campo Size é obrigatório"

    DeleteBadRequestType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "O campo Id do personagem é obrigatório"

    NotFoundType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "Character 123 não encontrado"

    ConflictType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "O Character 123 ja existe."

    InternalServerEerrorType:
      allOf:
        - $ref: '#/components/schemas/ExceptionResponseType'
        - type: object
          example:
            details:
              - "Banco de dados off-line"

    # [TYPE :: RESPONSE :: PERSONAGEM]
    CharacterPageResponseType:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/paginationType'
        data:
          type: array
          items:
            $ref: '#/components/schemas/CharacterType'

    CharacterGetResponseType:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CharacterType'

    CharacterCreateResponseType:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CharacterType'

    CharacterUpdateResponseType:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CharacterType'

    # [TYPE :: PERSONAGEM]
    CharacterType:
      type: object
      properties:
        charId:
          $ref: '#/components/schemas/id-field'
        charRaceId:
          $ref: '#/components/schemas/id-field'
        charClassId:
          $ref: '#/components/schemas/id-field'
        name:
          $ref: '#/components/schemas/char-name-field'
        attributes:
          $ref: '#/components/schemas/AttributesType'

    AttributesType:
      type: object
      description: ''
      properties:
        life:
          type: integer
        damage:
          $ref: '#/components/schemas/DamageType'
        resistance:
          $ref: '#/components/schemas/ResistanceType'
        skils:
          $ref: '#/components/schemas/skils-field'

    DamageType:
      type: object
      description: ''
      properties:
        physical:
          type: integer
        magic:
          type: integer

    ResistanceType:
      type: object
      description: ''
      properties:
        physical:
          type: integer
        magic:
          type: integer



####
####
####
####
####