<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.3</version>
    </parent>

    <name>pegasus-api-rest-cover</name>
    <description>Aplicação CRUD {Pacodes em camadas, H2}.</description>

    <groupId>br.com.pegasus</groupId>
    <artifactId>pegasus-api-rest-cover</artifactId>
    <version>1.0.0</version>

    <properties>
        <!-- PATHs -->
        <path.resources>${project.basedir}/src/main/resources</path.resources>

        <!-- GERAL -->
        <java.version>17</java.version>
        <compilation.build>${maven.build.timestamp}</compilation.build>

        <!-- OPEN-API -->
        <path.resources.openapi>${path.resources}/openapi</path.resources.openapi>
        <openapi.root-package>br.com.pegasus.swagger</openapi.root-package>
        <openapi.apiPackage>${openapi.root-package}.web.personagens</openapi.apiPackage>
        <openapi.templateDirectory>${path.resources.openapi}/mustache</openapi.templateDirectory>
        <openapi.ignoreFileOverride>${path.resources.openapi}/.openapiignore</openapi.ignoreFileOverride>

        <!-- CONTRATO :: MAIN -->
        <openapi.main.id>contract-main</openapi.main.id>
        <openapi.main.inputSpec>${path.resources.openapi}/openapi.yaml</openapi.main.inputSpec>
        <openapi.main.modelPackage>${openapi.root-package}.character.type</openapi.main.modelPackage>
        <!-- CONTRATO :: MODEL -->
        <openapi.model.id>contract-model</openapi.model.id>
        <openapi.model.inputSpec>${path.resources.openapi}/contracts/openapi-model.yaml</openapi.model.inputSpec>
        <openapi.model.modelPackage>${openapi.root-package}.character.model</openapi.model.modelPackage>
        <!-- CONTRATO :: ENTITY -->
        <openapi.entity.id>contract-entity</openapi.entity.id>
        <openapi.entity.inputSpec>${path.resources.openapi}/contracts/openapi-entity.yaml</openapi.entity.inputSpec>
        <openapi.entity.modelPackage>${openapi.root-package}.character.entity</openapi.entity.modelPackage>
        <!-- CONTRATO :: UTIL -->
        <openapi.util.id>contract-util</openapi.util.id>
        <openapi.util.inputSpec>${path.resources.openapi}/contracts/openapi-util.yaml</openapi.util.inputSpec>
        <openapi.util.modelPackage>${openapi.root-package}.util</openapi.util.modelPackage>

    </properties>

    <dependencies>
        <!-- Cria APIs RESTful e gerencia requisições HTTP -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Integração com Bean Validation (JSR 380) para validações com @Valid, @NotNull, etc -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>

        <!-- Validadores -->
        <dependency><!-- API da especificação Bean Validation (JSR 380): define anotações como @NotNull, @Size, etc -->
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>
        <dependency><!-- Implementação da API Bean Validation: executa validações em tempo de execução (@NotNull, @Size, @Email, etc)  -->
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>8.0.2.Final</version>
        </dependency>
        <dependency><!-- Anotações da JetBrains para análise estática (ex: @NotNull, @Nullable) em IDEs -->
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.0.2</version>
            <scope>compile</scope>
        </dependency>

        <!-- Fornece anotações padrão Jakarta como @PostConstruct, @PreDestroy; usado em REST, JPA e beans -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.1.1</version>
        </dependency>

        <!-- Geração automática de métodos como getters, setters, toString, builder, etc. -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>compile</scope>
        </dependency>

        <!-- Banco de dados em memória leve para testes e desenvolvimento local -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- Integração com JPA para manipulação de dados e persistência em banco de dados -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- SWAGGER: Gera interface web interativa para testar e visualizar a API em /swagger-ui.html -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency><!-- SWAGGER: Gera código (client/server) com base no contrato OpenAPI -->
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator</artifactId>
            <version>7.14.0</version>
        </dependency>

        <dependency><!-- Conversão entre objetos Java e JSON -->
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <!-- Suporte para tipos modernos do Java (ex: LocalDate) na conversão JSON -->
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <!-- Mapeamento entre objetos (ex: de DTO para Entity e vice-versa) -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.5.5.Final</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin><!-- Empacotador maven (jar/war) -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin><!-- Compiler maven -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <annotationProcessorPaths>
                        <path>  <!-- Garante a geração dos métodos antes da execução do código -->
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.30</version>
                        </path>
                        <path> <!-- Garante a geração do mapper no momento da compilação -->
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.5.5.Final</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

            <!-- SWAGGER GENERATEGENERATE -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>

                <!-- CONTRATO :: MAIN -->
                <executions>
                    <execution>
                        <id>${openapi.main.id}</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <ignoreFileOverride>${openapi.ignoreFileOverride}</ignoreFileOverride>
                            <inputSpec>${openapi.main.inputSpec}</inputSpec>
                            <modelPackage>${openapi.main.modelPackage}</modelPackage>
                            <templateDirectory>${path.resources.openapi}</templateDirectory> <!-- USA DEFAULT -->
                            <apiPackage>${openapi.apiPackage}</apiPackage>

                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <skipValidateSpec>true</skipValidateSpec>
                            <generatorName>spring</generatorName>
                            <configOptions>
                                <async>true</async>
                                <booleanGetterPrefix>is</booleanGetterPrefix>
                                <dateLibrary>java8</dateLibrary>
                                <delegatePattern>true</delegatePattern>
                                <disableGeneratedAnnotation>true</disableGeneratedAnnotation>
                                <generateBuilders>true</generateBuilders>
                                <generateTests>false</generateTests>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <openApiNullable>false</openApiNullable>
                                <returnResponse>true</returnResponse>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useBeanValidation>false</useBeanValidation>
                                <useTags>true</useTags>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <generateTests>false</generateTests>
                            </configOptions>
                        </configuration>
                    </execution>

                    <!-- CONTRATO :: MODEL -->
                    <execution>
                        <id>${openapi.model.id}</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <ignoreFileOverride>${openapi.ignoreFileOverride}</ignoreFileOverride>
                            <inputSpec>${openapi.model.inputSpec}</inputSpec>
                            <modelPackage>${openapi.model.modelPackage}</modelPackage>
                            <templateDirectory>${openapi.templateDirectory}</templateDirectory>
                            <apiPackage>${openapi.apiPackage}</apiPackage>

                            <skipValidateSpec>true</skipValidateSpec>
                            <generatorName>spring</generatorName>
                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <configOptions>
                                <async>true</async>
                                <booleanGetterPrefix>is</booleanGetterPrefix>
                                <dateLibrary>java8</dateLibrary>
                                <disableGeneratedAnnotation>true</disableGeneratedAnnotation>
                                <delegatePattern>true</delegatePattern>
                                <generateBuilders>true</generateBuilders>
                                <generateTests>false</generateTests>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <openApiNullable>false</openApiNullable>
                                <returnResponse>true</returnResponse>
                                <useBeanValidation>false</useBeanValidation>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>

                    <!-- CONTRATO :: ENTITY -->
                    <execution>
                        <id>${openapi.entity.id}</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <ignoreFileOverride>${openapi.ignoreFileOverride}</ignoreFileOverride>
                            <inputSpec>${openapi.entity.inputSpec}</inputSpec>
                            <modelPackage>${openapi.entity.modelPackage}</modelPackage>
                            <templateDirectory>${openapi.templateDirectory}</templateDirectory>
                            <apiPackage>${openapi.apiPackage}</apiPackage>

                            <skipValidateSpec>true</skipValidateSpec>
                            <generatorName>spring</generatorName>
                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <configOptions>
                                <async>true</async>
                                <booleanGetterPrefix>is</booleanGetterPrefix>
                                <dateLibrary>java8</dateLibrary>
                                <disableGeneratedAnnotation>true</disableGeneratedAnnotation>
                                <delegatePattern>true</delegatePattern>
                                <generateBuilders>true</generateBuilders>
                                <generateTests>false</generateTests>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <openApiNullable>false</openApiNullable>
                                <returnResponse>true</returnResponse>
                                <useBeanValidation>false</useBeanValidation>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>

                    <!-- CONTRATO :: UTIL -->
                    <execution>
                        <id>${openapi.util.id}</id>
                        <goals><goal>generate</goal></goals>
                        <configuration>
                            <ignoreFileOverride>${openapi.ignoreFileOverride}</ignoreFileOverride>
                            <inputSpec>${openapi.util.inputSpec}</inputSpec>
                            <modelPackage>${openapi.util.modelPackage}</modelPackage>
                            <templateDirectory>${openapi.templateDirectory}</templateDirectory>
                            <apiPackage>${openapi.apiPackage}</apiPackage>

                            <skipValidateSpec>true</skipValidateSpec>
                            <generatorName>spring</generatorName>
                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <configOptions>
                                <async>true</async>
                                <booleanGetterPrefix>is</booleanGetterPrefix>
                                <dateLibrary>java8</dateLibrary>
                                <disableGeneratedAnnotation>true</disableGeneratedAnnotation>
                                <delegatePattern>true</delegatePattern>
                                <generateBuilders>true</generateBuilders>
                                <generateTests>false</generateTests>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <openApiNullable>false</openApiNullable>
                                <returnResponse>true</returnResponse>
                                <useBeanValidation>false</useBeanValidation>
                                <useSpringBoot3>true</useSpringBoot3>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>

                </executions>
            </plugin>

        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/wpoliveiragit/maven-repository</url>
        </repository>
    </distributionManagement>

</project>
