# ==============================
# DATABASE - Configurações do Banco de Dados H2
# ==============================
spring.datasource.url: 'jdbc:h2:file:./src/main/resources/data/testdb'  # URL do banco de dados (armazenado localmente em arquivo)
spring.datasource.driver-class-name: 'org.h2.Driver'  # Driver do banco de dados H2
spring.datasource.username: 'sa'  # Usuário do banco de dados
spring.datasource.password: ''  # Senha do banco de dados (vazia)
spring.jpa.database-platform: 'org.hibernate.dialect.H2Dialect'  # Dialeto do Hibernate para H2

# ==============================
# CONSOLE H2 - Acesso ao Console do H2 via Navegador
# ==============================
spring.h2.console.enabled: true  # Habilita o console do H2
spring.h2.console.path: /h2-console  # Define o caminho para acessar o console no navegador (ex: http://localhost:8080/h2-console)

# ==============================
# JPA - Configurações de Persistência
# ==============================
spring.jpa.show-sql: true  # Exibe as consultas SQL geradas pelo JPA no console
spring.jpa.hibernate.ddl-auto: create  # Define o comportamento do Hibernate em relação ao esquema do banco (no caso, cria o esquema e apaga os dados existentes)
hibernate.dialect: org.hibernate.dialect.H2Dialect  # Dialeto específico do H2 para o Hibernate

# ==============================
# LOG - Configuração de Logs
# ==============================
logging.level.org.springframework: INFO
logging.level.org.springframework.security: DEBUG
logging.level.com.exemplo.hexagonal: DEBUG

# LOG - Desativa logs de segurança
logging.level.org.springframework.security.web.DefaultSecurityFilterChain: OFF
logging.level.org.springframework.security.web.authentication.AnonymousAuthenticationFilter: OFF
logging.level.org.springframework.security.web.FilterChainProxy: OFF
logging.level.org.springframework.security.web.savedrequest.HttpSessionRequestCache: OFF
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: OFF

# ==============================
# BANNER - Informações de Compilação e Versão
# ==============================
app.property.java.version: '@java.version@'
app.property.compilation.build: '@compilation.build@'
app.groupId: '@project.groupId@'
app.artifactId: '@project.artifactId@'
app.version: '@project.version@'
app.name: '@project.name@'
app.description: '@project.description@'

springdoc:
  swagger-ui:
    path: /swagger-ui.html