# DATABASE - Conexão com H2
#spring.datasource.url: 'jdbc:h2:mem:testdb'
#spring.datasource.url: 'jdbc:h2:classpath:/data/testdb;DB_CLOSE_DELAY=-1'
spring.datasource.url: 'jdbc:h2:file:./src/main/resources/data/testdb'
spring.datasource.driver-class-name: 'org.h2.Driver'
spring.datasource.username: 'sa'
spring.datasource.password: ''
spring.jpa.database-platform: 'org.hibernate.dialect.H2Dialect'

# DATABASE - console do H2
spring.h2.console.enabled: true # Ativa o console via navegador
spring.h2.console.path: /h2-console # Definição do path (ex.: http://localhost:8080/h2-console)

# JPA - configurações
spring.jpa.show-sql: true # Mostra o SQL usado pelo JPA
spring.jpa.hibernate.ddl-auto: create
hibernate.dialect: org.hibernate.dialect.H2Dialect
# none:_________ Não realiza nenhuma ação no banco de dados.
# validate:_____ Verifica se o esquema do banco está consistente com as entidades, sem alterá-lo.
# update:_______ Sincroniza o esquema com as entidades. Mantém dados e tabelas existentes.
# create:_______ Gera o esquema do banco com base nas entidades. Apaga os dados anteriores.
# create-drop:__ Idem ao 'create', mas remove o esquema ao encerrar o aplicativo.

# LOG - CONFIGURAÇÃO
#logging.pattern.console: '[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] [%logger{0}] :: %highlight(%msg%n)'
#logging.pattern.console: '%yellow([%d{yyyy-MM-dd HH:mm:ss}] [%-5level] [%logger{0}] :: %msg%n)'
#logging.pattern.console: '[%yellow(%d{yyyy-MM-dd HH:mm:ss})] [%highlight(%-5level)] [%cyan(%thread)] [%blue(%logger{36})] :: %msg%n'

# LOG - STATUS
logging.level.org.springframework: INFO
logging.level.org.springframework.security: DEBUG
logging.level.com.exemplo.hexagonal: DEBUG

# LOG - DESATIVA SECURITY
logging.level.org.springframework.security.web.DefaultSecurityFilterChain: OFF
logging.level.org.springframework.security.web.authentication.AnonymousAuthenticationFilter: OFF
logging.level.org.springframework.security.web.FilterChainProxy: OFF
logging.level.org.springframework.security.web.savedrequest.HttpSessionRequestCache: OFF
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: OFF

# BANNER
app.property.java.version: '@java.version@'
app.property.compilation.build: '@compilation.build@'
app.groupId: '@project.groupId@'
app.artifactId: '@project.artifactId@'
app.version: '@project.version@'
app.name: '@project.name@'
app.description: '@project.description@'
